default_folder = ["results_0810/RGHM_N_10_b_006"]
default_file_code = [[1, 351]]
#default_para_use = ["", 0]
default_para_use = ["r", 0]
default_x_use = 1 # From 0
default_x_range = [-2, 2, 501]
default_ob_use = [0, 1]
default_ob_interval = [["x", -2, 2], ["y", -2, 2]]
#default_ob_interval = [["x", 1, 1.6], ["y", -0.6, 0.6]]
default_ps_use = [0, -1, -2]
default_ps_interval = [["x", -2, 2], ["y", -2, 2], ["z", -2, 2]]
name_code_length = 5 #include a.cde -> 5 